require("dotenv").config()
const mongoose = require("mongoose")
const User = require("./models/user.model")
const casual = require("casual")

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI)

    await mongoose.connection.db.dropDatabase()
    console.log("Seeding please wait...")
    await Promise.all([
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/237/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird"]
      }),

      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/1044/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Mon", "Tues", "Thurs"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/1027/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Mon", "Tue", "Fri", "Sun"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/1062/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Tue", "Wed", "Fri", "Sat", "Sun"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/1082/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Thurs", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/1084/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Mon", "Wed", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/134/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Thurs", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/135/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog","Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/136/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat","Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/137/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Fri", "Sat", "Sun"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/140/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/139/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Fri"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/142/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Tue", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Cat", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/146/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Mon", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/15/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Thurs", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat",  "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/147/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/155/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Fri", "Sun"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/169/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/183/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Tues", "Fri", "Thurs"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat","Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/188/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Thurs", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/189/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Mon", "Wed", "Fri"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/191/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Tues", "Wed", "Sat", "Sun"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat","Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/190/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/191/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Mon", "Wed", "Fri", "Sun"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/199/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Mon", "Thurs", "Fri"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog","Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/200/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/203/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Wed", "Fri", "Sat", "Sun"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/211/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Thurs", "Fri", "Sat"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Pocket pet"]
      }),
      User.create({
        fullName: casual.full_name,
        email: casual.email,
        password: "123456",
        isDogsitter: true,
        city: casual.city,
        address: casual.address,
        phoneNumber: casual.phone,
        profilePhoto: "https://picsum.photos/id/219/200/300",
        about: casual.description,
        payments: [],
        isAvailable: true,
        availabilityDays: ["Mon", "Wed", "Fri", "Sun"],
        price: casual.integer(10, 50),
        petSittingCategory: ["Dog", "Cat", "Bird", "Pocket pet"]
      }),
    ])
    console.log("Completed seeding all dogsitters")
  } catch (error) {
    console.error(error)
    process.exit(1)
  } finally {
    console.log("Closing db connection...")
    await mongoose.disconnect()
    console.log("DB connection closed.")
  }
}

if (module === require.main) {
  seed()
}
